[package]
name = "fitch-style"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["Yonatan Kremer"]
description = "Fitch-style proof diagrams"
repository = "https://github.com/ykrem/fitch-style"
categories = ["visualization"]
disciplines = ["mathematics", "philosophy", "computer-science"]