[package]
name = "fitch-style"
version = "0.4.0"
entrypoint = "lib.typ"
authors = ["Yonatan Kremer"]
description = "Fitch-style proof diagrams."
repository = "https://github.com/ykrem/fitch-style"
categories = ["visualization"]
disciplines = ["mathematics","philosophy","computer-science"]